const mongoose = require("mongoose");
const dns = require("dns");
dns.setServers(["8.8.8.8", "8.8.4.4"]);
require("dotenv").config({ path: __dirname + "/.env" });
const Tour = require("./models/tours");

const tours = [
  // ===== 1. Forts & Trekking =====
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Sinhagad_Fort.jpg/960px-Sinhagad_Fort.jpg",
    name: "Sinhagad Fort",
    category: "Forts & Trekking",
    price: 1200,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Experience the majestic history and stunning sunset views of Sinhagad Fort, a signature hill fortress near Pune. Trek through the historic Kalyan Darwaza and savor local culinary delights like Pithla Bhakri at the top.",
    introduction: "Discover one of the most famous hill forts of Maharashtra, standing proudly in the Sahyadri mountains."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Rajgad_Fort.jpg/1280px-Rajgad_Fort.jpg",
    name: "Rajgad Fort",
    category: "Forts & Trekking",
    price: 2500,
    groupCount: 12,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Pune",
    description: "Trek to the former capital of the Maratha Empire under Chhatrapati Shivaji Maharaj. Explore the massive Padmavati Padmavati Machi, Sanjeevani Machi, and climb the steep Balekilla for a mesmerizing view.",
    introduction: "Explore the king of all forts, known for its rich history and grand fortifications."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Torna_entrance.jpg/1280px-Torna_entrance.jpg",
    name: "Torna Fort",
    category: "Forts & Trekking",
    price: 1500,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Trek to the highest fort in Pune district, also known as Prachandagad. Walk along the scenic ridge and explore the beautiful Zunjar Machi bastions, surrounded by Sahyadri peaks.",
    introduction: "Step onto the first fort captured by Shivaji Maharaj at the young age of 16."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/c/c0/View_of_Lohgad.jpg",
    name: "Lohagad Fort",
    category: "Forts & Trekking",
    price: 1100,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Lonavala",
    description: "Explore the 'Iron Fort' featuring the famous Vinchukata point (scorpion's tail structure) and a beautiful blend of ancient caves, huge gates, and lush green monsoon valleys.",
    introduction: "A beautiful and accessible trek ideal for beginners, rich in history and monsoon views."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Visapurfort.jpg/1280px-Visapurfort.jpg",
    name: "Visapur Fort",
    category: "Forts & Trekking",
    price: 1100,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Lonavala",
    description: "A companion to Lohagad, Visapur is famous for its gushing staircase waterfall trek during the monsoons. Explore the old ruins, water reservoirs, and the large stone cannon at the top.",
    introduction: "Walk up a staircase flowing with water in this unique monsoon trek near Pune."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Tikona_mid.jpg/1280px-Tikona_mid.jpg",
    name: "Tikona Fort",
    category: "Forts & Trekking",
    price: 1200,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Kamshet",
    description: "Trek to the triangular hill fort overlooking the serene Pawna lake. Climb the steep stone steps leading to the Trimbakeshvar Mahadev temple and take in the panoramic vistas.",
    introduction: "Discover the Pyramidal fort of Sahyadri, offering breathtaking lake views."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Korigad_sometimes.jpg/1280px-Korigad_sometimes.jpg",
    name: "Korigad Fort",
    category: "Forts & Trekking",
    price: 1300,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Lonavala",
    description: "A scenic trek to a fort near Amby Valley, famous for its completely intact ramparts, deep ponds, and massive cannons that still stand guard over the valley.",
    introduction: "Enjoy an easy and highly rewarding hill climb with vast tabletop fort landscapes."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Kalbhairav_pinnacle_Scj.jpg/1280px-Kalbhairav_pinnacle_Scj.jpg",
    name: "Harishchandragad",
    category: "Forts & Trekking",
    price: 2800,
    groupCount: 12,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Ahmednagar",
    description: "Trek to the ancient hill fort famous for the Konkan Kada, a massive semicircular vertical cliff, and the mysterious Kedareshwar cave temple with a monolith Shiva Linga.",
    introduction: "Challenge yourself with one of the most scenic and historic treks in Western Ghats."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Andharban_Forest.jpg/1280px-Andharban_Forest.jpg",
    name: "Andharban Trek",
    category: "Forts & Trekking",
    price: 1800,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Tamhini Ghat",
    description: "Walk through the 'Dark Forest Trek' surrounded by deep valleys, waterfalls, and dense foliage where sunlight barely touches the ground. Savor the peacefulness of nature.",
    introduction: "Immerse yourself in a dense jungle walk that descends from the ghats into the plains."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Devkund_Waterfall.JPG/1280px-Devkund_Waterfall.JPG",
    name: "Devkund Waterfall Trek",
    category: "Forts & Trekking",
    price: 1600,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Bhira",
    description: "Trek through the dense Bhira forest to the hidden Devkund waterfall, a confluence of three streams plunging into a beautiful turquoise pool enclosed by spectacular rocky cliffs.",
    introduction: "Trek to the 'pond of gods' and witness the pristine waterfall pool hidden in forests."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Western_Ghats_near_Pune.jpg",
    name: "Hatti Dongar",
    category: "Forts & Trekking",
    price: 1400,
    groupCount: 12,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Trek up the elephant-shaped hill near Pune, featuring pristine trails and serene, untouched nature views. A perfect offbeat escape from busy city life.",
    introduction: "Discover an offbeat trekking trail shaped like an elephant's back."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Sandhanvalley-2023.jpg",
    name: "Sandhan Valley",
    category: "Forts & Trekking",
    price: 2900,
    groupCount: 10,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Bhandardara",
    description: "Explore the 'Valley of Shadows', a unique water-carved canyon offering an adventurous trekking, bouldering, and rappelling experience between giant stone walls.",
    introduction: "Walk the path of shadows in Asia's second-largest rock canyon valley."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Pratapgad_The_Fort_of_Valour.jpg/1280px-Pratapgad_The_Fort_of_Valour.jpg",
    name: "Pratapgad Fort",
    category: "Forts & Trekking",
    price: 1500,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Mahabaleshwar",
    description: "Visit the historic fort near Mahabaleshwar, famous for the historic battle between Shivaji Maharaj and Afzal Khan. Walk through the giant bastions and explore the Afzal Tower.",
    introduction: "Relive history at the towering fortress that defined Maratha military architecture."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Rohida_1930168465.jpg/1280px-Rohida_1930168465.jpg",
    name: "Rohida Fort",
    category: "Forts & Trekking",
    price: 1300,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Bhor",
    description: "Also known as Vichitragad, this fort offers scenic bastion views, historic stone gates, and a delightful windy trek during rains, perfect for family hikes.",
    introduction: "Climb up the bastion gates of Rohida, surrounded by vast green Bhor valleys."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Lingana_pinnacle.jpg/1280px-Lingana_pinnacle.jpg",
    name: "Lingana Trek",
    category: "Forts & Trekking",
    price: 3200,
    groupCount: 8,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Pune",
    description: "A massive rock pinnacle offering an extreme climbing, rappelling, and trekking experience for adventure enthusiasts. Climb the challenging rock face under expert guidance.",
    introduction: "Face the ultimate Sahyadri challenge on the steep rock pinnacle of Lingana."
  },

  // ===== 2. Nature & Camping =====
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&auto=format&fit=crop&q=80",
    name: "Pawna Lake Camping",
    category: "Nature & Camping",
    price: 1600,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Kamshet",
    description: "Camp right by the waters of Pawna Lake. Enjoy live music, a cozy bonfire, stargazing sessions, and delicious local barbecue under the clear night sky.",
    introduction: "Relax at the lakeside with a classic tent camping experience near Lonavala."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=800&auto=format&fit=crop&q=80",
    name: "Mulshi Dam",
    category: "Nature & Camping",
    price: 1800,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Mulshi",
    description: "Spend a tranquil day by Mulshi Lake. Drive through the mist, hike to waterfalls, and stay in rustic cottages overlooking the forest-framed reservoir.",
    introduction: "Discover the lush green lakeside views and misty mountains around Mulshi Dam."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1478131143081-d0f52d428fa6?w=800&auto=format&fit=crop&q=80",
    name: "Tamhini Ghat",
    category: "Nature & Camping",
    price: 1200,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Mulshi",
    description: "Take a scenic drive through Tamhini Ghat, which transforms into a green paradise in monsoons with dozens of waterfalls, green mist, and pristine streams.",
    introduction: "Experience the ultimate monsoon drive through a mountain pass of waterfalls."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?w=800&auto=format&fit=crop&q=80",
    name: "Panshet Dam",
    category: "Nature & Camping",
    price: 1500,
    groupCount: 25,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "A popular lakeside getaway offering exciting water sports, speed boating, kayaking, and serene sunset views over the backwaters of Panshet Dam.",
    introduction: "Enjoy water rides and lakeside picnics at this famous dam near Pune."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1496080174650-63793c6ff971?w=800&auto=format&fit=crop&q=80",
    name: "Khadakwasla Lake",
    category: "Nature & Camping",
    price: 900,
    groupCount: 30,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Relax by the shores of Khadakwasla, enjoy fresh roasted corn on the cob (Bhutta), watch the sunset, and take a quick dip in the refreshing lake waters.",
    introduction: "Pune's favorite evening hangout spot, offering calm waters and beautiful sunsets."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1537905569824-f89f14cceb68?w=800&auto=format&fit=crop&q=80",
    name: "Bhor Backwaters",
    category: "Nature & Camping",
    price: 1700,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Bhor",
    description: "Camp along the secluded backwaters of Bhatghar Dam in Bhor. Perfect for a quiet weekend of bird watching, stargazing, and connecting with nature.",
    introduction: "Escape the tourist crowds at the quiet, peaceful backwaters of Bhor."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&auto=format&fit=crop&q=80",
    name: "Kaas Plateau",
    category: "Nature & Camping",
    price: 2200,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Satara",
    description: "Explore the UNESCO World Natural Heritage Site. Visit in late monsoon to see the plateau covered in a colorful carpet of wild flowers of thousands of species.",
    introduction: "Witness the 'Valley of Flowers' of Maharashtra at Kaas Plateau."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=800&auto=format&fit=crop&q=80",
    name: "Thoseghar Waterfalls",
    category: "Nature & Camping",
    price: 1300,
    groupCount: 25,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Satara",
    description: "Witness the gushing series of waterfalls ranging from 15 to 200 meters. Walk through the scenic viewing platforms and listen to the thunderous sound of water.",
    introduction: "Visit one of the highest and most spectacular waterfall systems in Maharashtra."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1511497584788-876760111969?w=800&auto=format&fit=crop&q=80",
    name: "Bhandardara",
    category: "Nature & Camping",
    price: 2400,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Akole",
    description: "Camp by Arthur Lake, visit the ancient Amruteshwar Temple, explore Randha Falls, and enjoy the pristine, pollution-free atmosphere surrounded by Saptashrungi ranges.",
    introduction: "A beautiful hill station village surrounded by lakes, waterfalls, and high peaks."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
    name: "Randha Falls",
    category: "Nature & Camping",
    price: 1100,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Akole",
    description: "Watch the clean Pravara River plunge down a 170-foot high gorge, creating a majestic misty white waterfall that is a true marvel during monsoons.",
    introduction: "See the breathtaking Randha Falls, a major clean energy source and scenic point."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&auto=format&fit=crop&q=80",
    name: "Malshej Ghat",
    category: "Nature & Camping",
    price: 1600,
    groupCount: 18,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Thane",
    description: "Drive through dense clouds, see pink flamingos near Pimpalgaon Joga dam, and feel the cold spray of numerous roadside waterfalls along the cliffs of Malshej.",
    introduction: "Experience a mountain pass famous for its unique flora, fauna, and waterfalls."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1433832597046-4f10e10ac764?w=800&auto=format&fit=crop&q=80",
    name: "Bhimashankar",
    category: "Nature & Camping",
    price: 1900,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Khed",
    description: "Explore the Bhimashankar Wildlife Sanctuary, home to the rare Giant Squirrel (Shekru). Trek through thick green rainforest paths and visit the Jyotirlinga temple.",
    introduction: "Discover the dense sanctuary forest and the source of the Bhima River."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?w=800&auto=format&fit=crop&q=80",
    name: "Koyna Backwaters",
    category: "Nature & Camping",
    price: 2600,
    groupCount: 12,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Koynanagar",
    description: "Enjoy boat rides in Shivsagar Lake (Koyna backwaters), surrounded by dense Koyna Wildlife Sanctuary. Perfect for jungle camping and spotting exotic birds.",
    introduction: "A secluded nature paradise nestled between the Western Ghats and Koyna Dam."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&auto=format&fit=crop&q=80",
    name: "Bhushi Dam",
    category: "Nature & Camping",
    price: 1000,
    groupCount: 25,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Lonavala",
    description: "Sit on the dam steps as water overflows over them. A highly popular, vibrant tourist spot during the monsoon season for friends and family alike.",
    introduction: "Lonavala's signature weekend spot, famous for its water-overflow steps."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&auto=format&fit=crop&q=80",
    name: "Tapola",
    category: "Nature & Camping",
    price: 2300,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Mahabaleshwar",
    description: "Known as the 'Mini Kashmir' of Maharashtra, Tapola offers a beautiful lake view, water sports, kayaking, and camping on remote farms across the Koyna backwaters.",
    introduction: "Enjoy water sports and tranquil lakeside camping in the foothills of Mahabaleshwar."
  },

  // ===== 3. Heritage & Culture =====
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/The_entrance_of_Shaniwar_Wada..JPG/1280px-The_entrance_of_Shaniwar_Wada..JPG",
    name: "Shaniwar Wada",
    category: "Heritage & Culture",
    price: 500,
    groupCount: 30,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Walk through the magnificent stone fortifications of Shaniwar Wada, the historic seat of the Peshwas. Explore the Delhi Darwaza, the ruins of the main palace, and the beautiful gardens.",
    introduction: "Step into the iconic 18th-century palace fort that defines the history of Pune."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/The_front_view_of_Aga_Khan_Palace..JPG/1280px-The_front_view_of_Aga_Khan_Palace..JPG",
    name: "Aga Khan Palace",
    category: "Heritage & Culture",
    price: 600,
    groupCount: 25,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Visit the Italian-arch palace built in 1892, which served as a prison for Mahatma Gandhi during the freedom struggle. Explore Gandhi's ashes memorial and the peaceful green lawns.",
    introduction: "An elegant Italian-style palace linked closely to India's freedom struggle."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Laal_Mahal_2.jpg/1280px-Laal_Mahal_2.jpg",
    name: "Lal Mahal",
    category: "Heritage & Culture",
    price: 400,
    groupCount: 30,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Explore the red brick palace where Shivaji Maharaj spent his childhood. Witness the historic paintings depicting key events in his life, located in the heart of Pune.",
    introduction: "A symbolic red palace celebrating Shivaji Maharaj's early life and victories."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Building_of_Raja_Dinkar_Kelkar_Museum%2C_Pune.jpg/1280px-Building_of_Raja_Dinkar_Kelkar_Museum%2C_Pune.jpg",
    name: "Raja Dinkar Kelkar Museum",
    category: "Heritage & Culture",
    price: 800,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Admire the vast personal collection of Dr. Kelkar, featuring ancient Indian instruments, copper vessels, paintings, lamps, and the replica of the Mastani Mahal palace hall.",
    introduction: "A fascinating museum displaying Indian art, craftsmanship, and daily-use items."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Punwadi_to_punyanagri_on_tulsi_bagh%2CPune%2CIndia.JPG/1280px-Punwadi_to_punyanagri_on_tulsi_bagh%2CPune%2CIndia.JPG",
    name: "Vishrambaug Wada",
    category: "Heritage & Culture",
    price: 400,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Walk past the carved wooden pillars of this historic 3-story mansion built by Peshwa Bajirao II. It stands as a beautiful example of Maratha-style woodwork and architectural style.",
    introduction: "See the majestic wooden balcony and Maratha design at Vishrambaug Wada."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/5/53/Kasba_Ganapati.jpg",
    name: "Kasba Ganpati",
    category: "Heritage & Culture",
    price: 300,
    groupCount: 40,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Seek blessings at the temple of Pune's 'Manacha Pahila' (First deity) Ganpati. Established by Jijabai in the 17th century, it is central to the culture and history of Pune.",
    introduction: "Visit the historic temple that marks Pune's spiritual core and first Ganpati."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Dagdusheth_Halwai_Ganpati_2025.jpg/960px-Dagdusheth_Halwai_Ganpati_2025.jpg",
    name: "Dagdusheth Temple",
    category: "Heritage & Culture",
    price: 300,
    groupCount: 50,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Offer prayers at the world-famous Shreemant Dagdusheth Halwai Ganpati Temple, known for its gold-decorated deity and a beautiful architectural setup visited by millions every year.",
    introduction: "Experience the vibrant spiritual energy of Pune's most famous Ganpati temple."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Pataleshwar_Temple_1.jpg/1280px-Pataleshwar_Temple_1.jpg",
    name: "Pataleshwar Cave Temple",
    category: "Heritage & Culture",
    price: 300,
    groupCount: 25,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Walk inside the 8th-century rock-cut Shiva temple carved out of a single basalt rock, featuring a circular Nandi canopy and an incredibly peaceful courtyard in Pune's center.",
    introduction: "Discover an ancient rock-cut cave temple hidden right in the busy city center."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Crowded_street_of_Tulshibaug%2C_Pune.jpg/1280px-Crowded_street_of_Tulshibaug%2C_Pune.jpg",
    name: "Tulshibaug",
    category: "Heritage & Culture",
    price: 400,
    groupCount: 30,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Explore the historic market area around the Tulshibaug Ram Temple. Savor local snacks and shop for traditional brass items, jewelry, clothes, and copper utensils.",
    introduction: "Explore Pune's oldest, most vibrant bazaar and the historic Ram Temple."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/5/59/Pune_montage.png",
    name: "Old Pune Heritage Walk",
    category: "Heritage & Culture",
    price: 900,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Take a guided walking tour through Pune's historic 'Peths', passing old wooden Wadas, traditional markets, Ganpati shrines, and colonial structures, ending with tea.",
    introduction: "Walk the path of history through the narrow lanes of old Pune city."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Trimbakeshwar_1.jpg/960px-Trimbakeshwar_1.jpg",
    name: "Trimbakeshwar Temple",
    category: "Heritage & Culture",
    price: 1800,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Nashik",
    description: "Visit the sacred Jyotirlinga temple at the source of the Godavari River. Admire the black basalt architecture and experience the divine morning prayers.",
    introduction: "Experience spiritual bliss at the historic Trimbakeshwar Jyotirlinga."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Ajanta_%2863%29.jpg",
    name: "Ajanta Caves",
    category: "Heritage & Culture",
    price: 2500,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Aurangabad",
    description: "Marvel at the 30 rock-cut Buddhist cave monuments dating from the 2nd century BCE, featuring the world-famous Ajanta frescoes and sculptures depicting Jataka tales.",
    introduction: "Explore the UNESCO-listed ancient Ajanta caves, famous for masterpieces of art."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Ellora_Caves%2C_India%2C_Kailasanatha_Temple_2.jpg/1280px-Ellora_Caves%2C_India%2C_Kailasanatha_Temple_2.jpg",
    name: "Ellora Caves",
    category: "Heritage & Culture",
    price: 2500,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Aurangabad",
    description: "Visit the spectacular Kailash Temple (Cave 16), the largest monolithic rock excavation in the world, carved vertically down from the mountain top, alongside Buddhist and Jain caves.",
    introduction: "Witness the architectural miracle of Kailash Temple at Ellora Caves."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Daulatabad%2C_Aurangabad_-_panoramio_%28227%29.jpg/1280px-Daulatabad%2C_Aurangabad_-_panoramio_%28227%29.jpg",
    name: "Daulatabad Fort",
    category: "Heritage & Culture",
    price: 1600,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Aurangabad",
    description: "Climb the impregnable Devgiri fort, known for its ingenious defenses, the Chand Minar tower, and the dark tunnel (Bhulbhulaiya) that confused invading forces.",
    introduction: "Trek up the fortress of Devgiri, one of the most powerful medieval forts."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Shivneripic8.jpg/1280px-Shivneripic8.jpg",
    name: "Shivneri Fort",
    category: "Heritage & Culture",
    price: 1500,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Junnar",
    description: "Trek to the birthplace of Chhatrapati Shivaji Maharaj. Explore the Shivai Devi Temple, the birthplace room, and the Badami Talav water reservoir in Junnar.",
    introduction: "Visit the legendary hill fortress of Shivneri, birth soil of Shivaji Maharaj."
  },

  // ===== 4. Festivals & Local Events =====
  {
    currentUser: "admin@ruraltourism.com",
    img: "pune_ganesh_festival.jpg",
    name: "Pune Ganesh Festival",
    category: "Festivals & Local Events",
    price: 2500,
    groupCount: 30,
    languages: "Marathi, Hindi, English",
    duration: "3 Days",
    cities: "Pune",
    description: "Join the grand 10-day festival celebrations in Pune. Witness the heritage Dhol-Tasha troupes, visit the 5 traditional 'Manacha' Ganpatis, and join the final immersion procession.",
    introduction: "Experience the grandest, most colorful cultural festival of Maharashtra."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Jejuri_gadkot.jpg/1280px-Jejuri_gadkot.jpg",
    name: "Jejuri Bhandara Festival",
    category: "Festivals & Local Events",
    price: 1800,
    groupCount: 25,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Jejuri",
    description: "Witness the golden yellow spectacle of Jejuri, where Khadoba Temple is covered in tons of turmeric powder (Bhandara) by devotees dancing, singing, and chanting.",
    introduction: "Experience the vibrant, golden Bhandara festival of Jejuri Khadoba."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Decorated_entrance_of_Nivdunga_Vithoba_Temple_where_Sant_Tukaram_Palkhi_halted_in_Pune_during_the_Pandharpur_Wari_2023.jpg/1280px-Decorated_entrance_of_Nivdunga_Vithoba_Temple_where_Sant_Tukaram_Palkhi_halted_in_Pune_during_the_Pandharpur_Wari_2023.jpg",
    name: "Pandharpur Wari",
    category: "Festivals & Local Events",
    price: 3500,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "4 Days",
    cities: "Pandharpur",
    description: "Walk alongside millions of Warkaris chanting 'Gyanba Tukaram' in a spiritual walk of 21 days from Alandi/Dehu to the temple town of Pandharpur Vitthal Temple.",
    introduction: "Join the centuries-old, massive spiritual pilgrimage walk of Maharashtra."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Shivaji_British_Museum.jpg/960px-Shivaji_British_Museum.jpg",
    name: "Shiv Jayanti",
    category: "Festivals & Local Events",
    price: 1500,
    groupCount: 25,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Junnar",
    description: "Celebrate the birth anniversary of Shivaji Maharaj at Shivneri Fort. Witness traditional folk acts, lezim dance performances, dhol tasha, and historical plays.",
    introduction: "Join the proud, high-energy celebrations of Shivaji Maharaj's birthday."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/8/8a/2_Gaucher_Mela_Chamoli.jpg",
    name: "Village Jatra",
    category: "Festivals & Local Events",
    price: 1200,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Pune Rural",
    description: "Experience a traditional village fair (Jatra) with giant wheels, local sweet stalls (pedha, jalebi), wrestling competitions (Kusti), and village plays under the stars.",
    introduction: "Discover the rustic charm of a rural fair featuring local sports and sweets."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "lavani_performance.png",
    name: "Lavani Performance",
    category: "Festivals & Local Events",
    price: 1800,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Watch a live, high-energy performance of Lavani, the traditional dance form of Maharashtra, characterized by rapid dholki beats, foot tapping, and elegant expressions.",
    introduction: "Enjoy the expressive and rhythmic Marathi folk dance of Lavani."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "tamasha_show.png",
    name: "Tamasha Show",
    category: "Festivals & Local Events",
    price: 1700,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Satara",
    description: "Witness the traditional Marathi folk theatre form that combines music, dance, and satirical comedy, presented by touring groups at village centers.",
    introduction: "Relish a lively performance of Tamasha folk theater in rural Maharashtra."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Dahi_Handi.JPG/960px-Dahi_Handi.JPG",
    name: "Dahi Handi",
    category: "Festivals & Local Events",
    price: 1200,
    groupCount: 25,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Mumbai",
    description: "Join the Gokulashtami celebrations as human pyramids of Govindas challenge each other to break the hanging earthen pot filled with curd, milk, and dry fruits.",
    introduction: "Celebrate Lord Krishna's birthday with thrilling human pyramid events."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Bullock_Cart_Race.jpg/1280px-Bullock_Cart_Race.jpg",
    name: "Bullock Cart Race",
    category: "Festivals & Local Events",
    price: 1400,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune Rural",
    description: "Witness the fast-paced traditional racing sport of Maharashtra's farming villages, held during village yatras to display the strength and speed of local bulls.",
    introduction: "Experience the high-adrenaline rural sport of bullock cart racing."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Holi_Celebration_Huranga.jpg/1280px-Holi_Celebration_Huranga.jpg",
    name: "Holi Celebration",
    category: "Festivals & Local Events",
    price: 1500,
    groupCount: 30,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Celebrate Holi in a village setup with natural colors, traditional sweets (Puran Poli), community campfires (Holika Dahan), and local folk music sessions.",
    introduction: "Enjoy the festival of colors with organic powders and local food."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Diwali_at_our_village.jpg",
    name: "Diwali Village Festival",
    category: "Festivals & Local Events",
    price: 2800,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "3 Days",
    cities: "Satara Rural",
    description: "Experience a traditional Diwali celebration in a farming village. Light lamps, draw huge rangolis, enjoy home-cooked sweetmeats, and join the evening cattle worship (Vasu Baras).",
    introduction: "Witness the cozy, warm festival of lights in a village house setting."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/A_new_year_procession_on_Gudi_Padwa_festival%2C_Dombivli_Maharashtra.jpg/1280px-A_new_year_procession_on_Gudi_Padwa_festival%2C_Dombivli_Maharashtra.jpg",
    name: "Gudi Padwa",
    category: "Festivals & Local Events",
    price: 1300,
    groupCount: 25,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Celebrate the Maharashtrian New Year. Participate in raising the Gudi flag, enjoy Shrikhand-Puri feasts, and watch the grand colorful cultural rallies (Shobha Yatra).",
    introduction: "Welcome the Hindu New Year with traditional Maharashtrian rituals."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Mango_festival_at_Mayfair%2C_Guwahati.jpg/960px-Mango_festival_at_Mayfair%2C_Guwahati.jpg",
    name: "Mango Festival",
    category: "Festivals & Local Events",
    price: 1900,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Ratnagiri",
    description: "Join the harvest festival of the Alphonso mango. Savor unlimited fresh mangoes, participate in mango-based cooking workshops, and buy straight from the farmers.",
    introduction: "Savor the sweetness of fresh Alphonso mangoes at this local harvest event."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/8/83/Firefly_Music_Festival_Main_Stage%2C_July_2012.jpg",
    name: "Fireflies Festival",
    category: "Festivals & Local Events",
    price: 2100,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Bhandardara",
    description: "Witness millions of fireflies lighting up the night forest in a magical mating dance. Walk through quiet forest paths near Bhandardara Lake just before the monsoons.",
    introduction: "Walk under trees lit up by millions of fireflies at Bhandardara forest."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/2019_Feb_04_-_Kumbh_Mela_-_Allahabadi_Musicians_Perform.jpg/1280px-2019_Feb_04_-_Kumbh_Mela_-_Allahabadi_Musicians_Perform.jpg",
    name: "Rural Folk Music Night",
    category: "Festivals & Local Events",
    price: 1600,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Kolhapur",
    description: "Listen to the rich oral traditions of Gondhal, Bharud, and Powada, performed live by village musicians under the open skies around a warm bonfire.",
    introduction: "Immerse yourself in stories and devotional songs of Marathi folk music."
  },

  // ===== 5. Village Experience =====
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Cuba_casa_particular.jpg/1280px-Cuba_casa_particular.jpg",
    name: "Village Homestay",
    category: "Village Experience",
    price: 1800,
    groupCount: 10,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Satara",
    description: "Stay in a traditional home with a local family. Help cook in earthen pots, draw fresh water from the well, and enjoy the clean country air.",
    introduction: "Experience simple village life and hospitality with an authentic home stay."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Bullock_Cart_Ride.jpg/960px-Bullock_Cart_Ride.jpg",
    name: "Bullock Cart Ride",
    category: "Village Experience",
    price: 800,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune Rural",
    description: "Take a slow, rhythmic bullock cart ride through village pathways, farm fields, and dusty tracks, just like villagers have traveled for centuries.",
    introduction: "Enjoy the traditional cart ride through green farms and village roads."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/c/ca/%27B_M_X%27_STUNT_CYCLING.jpg",
    name: "Village Cycling Tour",
    category: "Village Experience",
    price: 1200,
    groupCount: 12,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Bhor",
    description: "Cycle along quiet roads, passing green paddy fields, old temples, and riverside backwaters. Stop for a refreshing sugarcane juice fresh from the farm.",
    introduction: "Explore rural beauty on two wheels, pedaling past farms and villages."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Organic-vegetable-cultivation.jpeg/1280px-Organic-vegetable-cultivation.jpeg",
    name: "Organic Farm Stay",
    category: "Village Experience",
    price: 2500,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Mulshi",
    description: "Stay at a working organic farm. Learn about permaculture, sow seeds, harvest seasonal vegetables, and enjoy fresh meals directly from the soil.",
    introduction: "Settle into a cozy cottage at a sustainable organic farm."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Visit_to_a_dairy_and_sheep_farm_%281522788%29.jpg/1280px-Visit_to_a_dairy_and_sheep_farm_%281522788%29.jpg",
    name: "Dairy Farm Visit",
    category: "Village Experience",
    price: 1100,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Kolhapur",
    description: "Visit a clean dairy farm. Try your hand at cow milking, learn how local dairy products are processed, and taste fresh, hot buffalo milk with sugar.",
    introduction: "Discover the daily operations of a rural dairy farm and try cow milking."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/A_simple_campfire.jpg/1280px-A_simple_campfire.jpg",
    name: "Village Bonfire",
    category: "Village Experience",
    price: 1400,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Panshet",
    description: "Sit around a crackling log fire on a cool evening. Listen to folklore narrated by village elders, stargaze, and roast sweet potatoes in the coals.",
    introduction: "Enjoy warm fireside chats, storytelling, and local snacks under stars."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Cappadociasunrise.jpg/1280px-Cappadociasunrise.jpg",
    name: "Rural Sunrise Walk",
    category: "Village Experience",
    price: 900,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Satara",
    description: "Wake up early for a guided walk up the village hill. Watch the sun rise over misty valleys and check out local birds nested in old banyan trees.",
    introduction: "Witness the beautiful morning sun rising over green hills and valleys."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Deepsea.JPG/1280px-Deepsea.JPG",
    name: "Local Fishing Experience",
    category: "Village Experience",
    price: 1300,
    groupCount: 12,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Khadakwasla",
    description: "Learn traditional rod-and-line fishing or net fishing in a village lake. Watch local fishermen catch fresh fish, and get tips from them.",
    introduction: "Spend a relaxing day learning how to catch fish in a village pond."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Rumunia_5806.jpg/1280px-Rumunia_5806.jpg",
    name: "Shepherd Experience",
    category: "Village Experience",
    price: 1500,
    groupCount: 10,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Jejuri",
    description: "Spend a day walking with a traditional shepherd community (Dhangars). Watch sheep grazing across grasslands and learn about their traditional lifestyle.",
    introduction: "Walk the green pasture lands with local shepherds and their sheep flocks."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/East_Front_of_Merahi_Village.jpg/1280px-East_Front_of_Merahi_Village.jpg",
    name: "Traditional House Visit",
    category: "Village Experience",
    price: 700,
    groupCount: 25,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune Rural",
    description: "Visit 100-year-old mud houses with wooden pillars and courtyards (Chauk). Learn about traditional clay plasters that keep houses cool in summer.",
    introduction: "Explore the old architecture and layout of classic village homes."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/08_Asper_1_-_Copy.jpg/960px-08_Asper_1_-_Copy.jpg",
    name: "Bamboo Village Tour",
    category: "Village Experience",
    price: 1600,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Velhe",
    description: "Visit a village famous for bamboo plantations. Walk through paths covered by bamboo forests, see the harvesting process, and meet local craftsmen.",
    introduction: "A scenic walk through green bamboo groves and local artisan houses."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/a/aa/George_Hansen_in_village_market._India._1967_%2817011975905%29.jpg",
    name: "Village Market Visit",
    category: "Village Experience",
    price: 900,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Bhor",
    description: "Visit the weekly village market (Athavadi Bazar). Experience the lively bargaining, see heaps of fresh village vegetables, spices, and handmade tools.",
    introduction: "Experience the colorful weekly local market of rural Maharashtra."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "local_temple_tour.png",
    name: "Local Temple Tour",
    category: "Village Experience",
    price: 1100,
    groupCount: 25,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Purandar",
    description: "Visit ancient stone temples located on hillocks and beside streams. Learn about the ancient architectural carvings, folklore, and local god myths.",
    introduction: "Discover the beautiful stone temples and shrines of old villages."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Grandmother_preparing_food_inside_traditional_kitchen_%28edited%29.jpg/1280px-Grandmother_preparing_food_inside_traditional_kitchen_%28edited%29.jpg",
    name: "Rural Cooking Experience",
    category: "Village Experience",
    price: 1900,
    groupCount: 12,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Satara",
    description: "Learn how to cook on a traditional clay stove (Chulha). Hand-grind spices on a stone grinder (Varvanta) and cook local dishes under guidance.",
    introduction: "Learn the secrets of traditional rural cooking using fresh ingredients."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "koli_dance.png",
    name: "Koli Dance",
    category: "Village Experience",
    price: 1500,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Kolhapur",
    description: "Participate in local folk dances like Koli dance and Fugdi during village gatherings. Dress in traditional attire and dance to the beat of drums.",
    introduction: "Join local villagers and dance along to classic Maharashtrian folk beats."
  },

  // ===== 6. Local Food Trails =====
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=800&auto=format&fit=crop&q=80",
    name: "Pune Misal Trail",
    category: "Local Food Trails",
    price: 900,
    groupCount: 25,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Taste the spicy Pune Misal Pav. Visit iconic spots (Kata Kirr, Bedekar) to experience the fiery sprouts gravy (Katt), farsan, and soft Pav buns.",
    introduction: "Savor the legendary spicy sprouts curry dish that is Pune's pride."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80",
    name: "Kolhapuri Food Tour",
    category: "Local Food Trails",
    price: 1800,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Kolhapur",
    description: "Enjoy a traditional Kolhapuri thali featuring the famous Tambda Rassa (spicy red gravy), Pandhra Rassa (white coconut gravy), Bhakri, and local mutton or veg fry.",
    introduction: "Relish the iconic, authentic spicy Kolhapuri thali experience."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=800&auto=format&fit=crop&q=80",
    name: "Village Bhakri Lunch",
    category: "Local Food Trails",
    price: 1100,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune Rural",
    description: "Sit on floor mats (Pata) and enjoy freshly made Bajri/Jowar Bhakri, hot spicy Pithla, green chili Thecha, raw onions, and freshly churned white butter.",
    introduction: "Enjoy a rustic farm lunch featuring hot Pithla Bhakri and Thecha."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=80",
    name: "Hurda Party",
    category: "Local Food Trails",
    price: 1600,
    groupCount: 30,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune Rural",
    description: "Participate in a winter Hurda Party. Feast on tender roasted jowar grains (Hurda) served with dry garlic chutney, peanut chutney, jaggery, and sesame sweets.",
    introduction: "Enjoy a winter harvest tradition, tasting fresh roasted tender jowar."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=800&auto=format&fit=crop&q=80",
    name: "Vaishali Breakfast",
    category: "Local Food Trails",
    price: 800,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Visit the iconic Vaishali restaurant on FC Road. Enjoy South Indian filter coffee, crispy SPDP, sponge idli, and vada, a true Puneri morning tradition.",
    introduction: "Experience Pune's most legendary breakfast spot on FC Road."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80",
    name: "SPDP Food Trail",
    category: "Local Food Trails",
    price: 700,
    groupCount: 30,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Explore the Puneri chat trail, highlighting Sev Potato Dahi Puri (SPDP), sweet yogurt-filled puris topped with fine sev, chutneys, and mango pulps.",
    introduction: "Savor the local chat creation of Pune - the famous sweet and tangy SPDP."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1605083637156-4c4f0db8269e?w=800&auto=format&fit=crop&q=80",
    name: "Modak Workshop",
    category: "Local Food Trails",
    price: 1500,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Learn how to make the Ukadiche Modak (steamed sweet dumplings filled with grated coconut and jaggery) using traditional methods of molding and steaming.",
    introduction: "Join a cooking class to mold and steam sweet Modaks yourself."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?w=800&auto=format&fit=crop&q=80",
    name: "Puran Poli Experience",
    category: "Local Food Trails",
    price: 1400,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Satara",
    description: "Master the art of rolling out Puran Poli (sweet flatbread filled with sweet lentil paste). Enjoy it hot with a dollop of pure homemade ghee.",
    introduction: "Learn to prepare the most popular festive sweet flatbread of Maharashtra."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=80",
    name: "Konkani Seafood Trail",
    category: "Local Food Trails",
    price: 2400,
    groupCount: 12,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Ratnagiri",
    description: "Travel to the coastal Konkan villages to taste Surmai/Kolambi fry, authentic fish curry with Solkadhi (tangy coconut drink with kokum), and rice bhakris.",
    introduction: "Taste fresh-catch seafood cooked in traditional Konkani coconut masala."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=800&auto=format&fit=crop&q=80",
    name: "Solapur Jowar Bhakri",
    category: "Local Food Trails",
    price: 1200,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Solapur",
    description: "Savor the dry, thin, and large Jowar Bhakris of Solapur, served with spicy Shenga Chutney (peanut chutney), curd, and spicy local black masala curry.",
    introduction: "Relish Solapur's famous thin sorghum bread served with local chutneys."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=800&auto=format&fit=crop&q=80",
    name: "Chitale Visit",
    category: "Local Food Trails",
    price: 800,
    groupCount: 30,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Visit a Chitale Bandhu store in Pune. Savor the crispy, spicy Bakarwadi, sweet Mango Barfi, and Shrikhand, learning about their rich culinary journey.",
    introduction: "Taste the legendary Bakarwadi and sweets of Pune's favorite shop."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=80",
    name: "Sugarcane Juice Farm",
    category: "Local Food Trails",
    price: 600,
    groupCount: 25,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune Rural",
    description: "Visit a sugarcane field and extract juice using a traditional diesel/bullock crusher. Drink it cold with ginger, lemon, and mint leaves.",
    introduction: "Crush and drink fresh, cold sugarcane juice right on a farm field."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1555126634-323283e090fa?w=800&auto=format&fit=crop&q=80",
    name: "Farmer's Breakfast",
    category: "Local Food Trails",
    price: 1000,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Satara",
    description: "Eat a hearty village breakfast of Pohe with grated coconut, spicy Misal, hot cups of tea, and freshly made multi-grain Thalipeeth with curd.",
    introduction: "Savor a traditional early morning breakfast on a farm field."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&auto=format&fit=crop&q=80",
    name: "Mango Orchard Lunch",
    category: "Local Food Trails",
    price: 2200,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Ratnagiri",
    description: "Dine under mango trees at an orchard. Enjoy Amras (sweet mango pulp) served with hot puris, local vegetables, papad, and spicy Konkan curries.",
    introduction: "Relish an Amras-Puri feast set inside a beautiful mango orchard."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=80",
    name: "Strawberry Farm Café",
    category: "Local Food Trails",
    price: 1500,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Mahabaleshwar",
    description: "Sip fresh strawberry milkshakes, enjoy strawberry cream desserts, and try out strawberry-infused pancakes at a farm cafe in Mahabaleshwar.",
    introduction: "Indulge in sweet strawberry cream desserts inside a strawberry farm."
  },

  // ===== 7. Farm Tourism =====
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1508873699372-7aeab60b44ab?w=800&auto=format&fit=crop&q=80",
    name: "Strawberry Farm",
    category: "Farm Tourism",
    price: 1500,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Mahabaleshwar",
    description: "Walk through rows of sweet strawberry plants in Mahabaleshwar. Pluck ripe red strawberries yourself, and learn about modern greenhouse farming.",
    introduction: "Sip strawberry cream and pick fresh strawberries in Mahabaleshwar."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1555126634-323283e090fa?w=800&auto=format&fit=crop&q=80",
    name: "Mango Orchard",
    category: "Farm Tourism",
    price: 2100,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Ratnagiri",
    description: "Visit the famous Alphonso mango farmlands in Devgad/Ratnagiri. Learn about grafting techniques and pluck mangoes straight from the trees.",
    introduction: "Explore rich mango farmlands and pluck fresh Alphonso mangoes."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800&auto=format&fit=crop&q=80",
    name: "Rice Plantation",
    category: "Farm Tourism",
    price: 1300,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune Rural",
    description: "Walk into muddy paddy fields and transplant young rice saplings. Experience the fun of monsoon farming and learn about traditional rice varieties.",
    introduction: "Get your feet wet transplanting rice saplings during monsoons."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop&q=80",
    name: "Grape Vineyard",
    category: "Farm Tourism",
    price: 2600,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Nashik",
    description: "Take a tour of grape plantations, learn about pruning, pick fresh grapes, and enjoy grape juice tasting sessions at a scenic Nashik vineyard.",
    introduction: "Stroll through Nashik's lush grape vineyards and taste fresh grapes."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&auto=format&fit=crop&q=80",
    name: "Sugarcane Farm",
    category: "Farm Tourism",
    price: 1100,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune Rural",
    description: "Walk between tall sugarcane stalks, see the harvesting process, cut sugarcane stalks using sickles, and eat sweet sugarcane core sections.",
    introduction: "Walk through towering sugarcane fields and chew on sweet sugarcane."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1568051243851-f9b136146e97?w=800&auto=format&fit=crop&q=80",
    name: "Dairy Farm",
    category: "Farm Tourism",
    price: 1400,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Kolhapur",
    description: "Visit a modern dairy farm featuring automated milkers and crossbreed cows. Milk cows, feed calves, and learn about the local milk co-operative system.",
    introduction: "Feed cows and try cow milking at a modern rural dairy farm."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?w=800&auto=format&fit=crop&q=80",
    name: "Vegetable Harvest",
    category: "Farm Tourism",
    price: 1000,
    groupCount: 25,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Satara Rural",
    description: "Pick fresh tomatoes, green chilies, brinjals, and gourds straight from the plants. Cook a fresh lunch using the organic vegetables you harvested.",
    introduction: "Harvest fresh organic vegetables and cook them immediately on site."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=800&auto=format&fit=crop&q=80",
    name: "Flower Farm",
    category: "Farm Tourism",
    price: 1500,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune Rural",
    description: "Walk through rows of bright orange marigolds, roses, and jasmine. Learn about traditional floriculture and how flowers are prepared for city markets.",
    introduction: "Explore fields of colorful marigolds and roses in full bloom."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1473081556163-2a17de81fc97?w=800&auto=format&fit=crop&q=80",
    name: "Beekeeping Experience",
    category: "Farm Tourism",
    price: 1800,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Mahabaleshwar",
    description: "Wear a protective suit and handle beehive frames. Watch honeybees work, learn how honey is extracted, and taste raw sweet honey comb.",
    introduction: "Observe honeybees and taste fresh honey straight from the comb."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1524024414332-2373199ff43e?w=800&auto=format&fit=crop&q=80",
    name: "Goat Farm",
    category: "Farm Tourism",
    price: 1200,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Satara",
    description: "Visit a modern stall-fed goat farm. Play with kids, feed them green fodder, and learn about the economics of small goat-farming setups.",
    introduction: "Feed goats, play with baby kids, and learn about goat farming."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1548550022-cbfaf1ae62c1?w=800&auto=format&fit=crop&q=80",
    name: "Poultry Farm",
    category: "Farm Tourism",
    price: 1100,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Bhor",
    description: "Visit a village poultry farm raising local Kadaknath and gavran chickens. Feed birds, collect fresh eggs, and understand cage-free poultry care.",
    introduction: "Collect fresh eggs and learn about rearing country chickens."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1605001011156-cbf0b0f67a51?w=800&auto=format&fit=crop&q=80",
    name: "Organic Farming",
    category: "Farm Tourism",
    price: 2000,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "2 Days",
    cities: "Panshet",
    description: "Spend two days learning compost making, natural pest control (Dashaparni), drip irrigation systems, and mulching at an organic farm.",
    introduction: "Master the basics of chemical-free, natural organic farming."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1587049633562-ad78524d521b?w=800&auto=format&fit=crop&q=80",
    name: "Coconut Farm",
    category: "Farm Tourism",
    price: 1700,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Ratnagiri",
    description: "Walk through a Konkan coconut grove, watch skilled climbers climb tall trees, and drink sweet fresh tender coconut water right in the shade.",
    introduction: "Drink fresh tender coconut water in a coastal coconut grove."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800&auto=format&fit=crop&q=80",
    name: "Spice Farm",
    category: "Farm Tourism",
    price: 1900,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Sindhudurg",
    description: "Take a walking tour of spice trees. See and smell black pepper vines, cardamom, nutmeg, cinnamon, and enjoy a traditional spicy buffet lunch.",
    introduction: "Discover spice trees like cardamom and pepper in a forest farm."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&auto=format&fit=crop&q=80",
    name: "Milking Experience",
    category: "Farm Tourism",
    price: 1200,
    groupCount: 12,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune Rural",
    description: "Wake up early at 5:00 AM to milk cows on a farm. Learn hand-milking techniques and experience dairy farming directly under guidance.",
    introduction: "Get hands-on experience milking cows early in the morning."
  },

  // ===== 8. Arts & Handicrafts =====
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&auto=format&fit=crop&q=80",
    name: "Warli Painting Workshop",
    category: "Arts & Handicrafts",
    price: 1200,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Palghar",
    description: "Learn the traditional tribal art form of Warli. Paint figures using white rice paste, mud bases, and bamboo brushes on clay pots or canvas.",
    introduction: "Create your own traditional tribal Warli painting with local artists."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1565192647048-f997ded87970?w=800&auto=format&fit=crop&q=80",
    name: "Pottery Workshop",
    category: "Arts & Handicrafts",
    price: 1400,
    groupCount: 12,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune Rural",
    description: "Sit behind a spinning potter's wheel. Mold wet clay into pots, bowls, and lamps under the guidance of a master village potter.",
    introduction: "Mold spinning wet clay into beautiful pots with a potter's wheel."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1508808789028-400a45820a4b?w=800&auto=format&fit=crop&q=80",
    name: "Bamboo Craft",
    category: "Arts & Handicrafts",
    price: 1300,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Velhe",
    description: "Learn how to weave thin bamboo strips into mats, baskets, lamp shades, and decorative artifacts directly from traditional bamboo artists.",
    introduction: "Weave dry bamboo strips into baskets and elegant lampshades."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&auto=format&fit=crop&q=80",
    name: "Kolhapuri Chappal Workshop",
    category: "Arts & Handicrafts",
    price: 1800,
    groupCount: 10,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Kolhapur",
    description: "Visit leather craftsmen in Kolhapur. See the process of design stamping, hand stitching, and oiling that gives Kolhapuri leather footwear its signature squeak.",
    introduction: "Learn the art of hand-stitching traditional leather Kolhapuri chappals."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80",
    name: "Paithani Weaving",
    category: "Arts & Handicrafts",
    price: 2500,
    groupCount: 10,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Paithan",
    description: "Visit traditional handloom weavers. Witness how pure silk and gold threads (Zari) are woven on wooden handlooms to create the famous peacock borders of Paithani sarees.",
    introduction: "Watch weavers spin gold and silk threads to create gorgeous Paithani sarees."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1528896925042-3e54fa4fb5cb?w=800&auto=format&fit=crop&q=80",
    name: "Handloom Experience",
    category: "Arts & Handicrafts",
    price: 1500,
    groupCount: 12,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Solapur",
    description: "Try weaving on a traditional handloom under guidance. Learn about cotton processing, yarn dyeing, and weaving traditional blankets and towels.",
    introduction: "Step up to a wooden handloom and weave cotton threads yourself."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80",
    name: "Copper Craft",
    category: "Arts & Handicrafts",
    price: 1700,
    groupCount: 10,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Visit Pune's copper beating community (Tambat Ali). Watch craftsmen heat, beat, and shape copper sheets into copper water bottles and decorative bowls.",
    introduction: "Observe copper beaters shape metal and learn their ancient techniques."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1606744824163-985d376605aa?w=800&auto=format&fit=crop&q=80",
    name: "Wood Carving",
    category: "Arts & Handicrafts",
    price: 1900,
    groupCount: 10,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune Rural",
    description: "Learn basic chiseling on blocks of wood. Create patterns like flowers and leaves under the supervision of local wood sculptors.",
    introduction: "Try wood chiseling and carving under the guidance of local sculptors."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?w=800&auto=format&fit=crop&q=80",
    name: "Clay Idol Making",
    category: "Arts & Handicrafts",
    price: 1600,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pen",
    description: "Visit Pen, the global hub of Ganesh clay idols. Learn how eco-friendly clay (Shadu mati) is cast into molds and hand-painted by local artists.",
    introduction: "Mold and paint eco-friendly Ganesh idols with clay artists."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=800&auto=format&fit=crop&q=80",
    name: "Rangoli Workshop",
    category: "Arts & Handicrafts",
    price: 1000,
    groupCount: 20,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Learn how to make traditional patterns (Sanskar Bharati) using colorful powders, grids, and sieves, perfect for welcoming festivals.",
    introduction: "Draw beautiful and colorful Rangoli designs on floor paths."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&auto=format&fit=crop&q=80",
    name: "Leather Craft",
    category: "Arts & Handicrafts",
    price: 1600,
    groupCount: 12,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune Rural",
    description: "Make small leather items like keychains, card holders, and wallets. Learn tracing, cutting, punch-stitching, and edge-finishing techniques.",
    introduction: "Stitch and create your own custom leather keychains and wallets."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1561715276-a2d087060f1d?w=800&auto=format&fit=crop&q=80",
    name: "Tribal Art Workshop",
    category: "Arts & Handicrafts",
    price: 1500,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Palghar",
    description: "Learn tribal art forms of Western Ghats communities, drawing animals, forests, and deities using organic color pastes on handmade paper.",
    introduction: "Create beautiful, colorful tribal paintings on handmade paper."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1508808789028-400a45820a4b?w=800&auto=format&fit=crop&q=80",
    name: "Bell Metal Craft",
    category: "Arts & Handicrafts",
    price: 1900,
    groupCount: 10,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune Rural",
    description: "Witness the lost-wax casting technique used to create brass and bell-metal figures like village lamps, cows, and mythological idols.",
    introduction: "Learn the ancient lost-wax casting process of metal crafts."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1604871000636-074fa5117945?w=800&auto=format&fit=crop&q=80",
    name: "Lantern Making",
    category: "Arts & Handicrafts",
    price: 1200,
    groupCount: 15,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Pune",
    description: "Build traditional Diwali sky lanterns (Akash Kandil) using thin wooden strips, colorful papers, glues, and matching borders under guidance.",
    introduction: "Craft a traditional hanging paper lantern to light up during festivals."
  },
  {
    currentUser: "admin@ruraltourism.com",
    img: "https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=800&auto=format&fit=crop&q=80",
    name: "Wooden Toy Workshop",
    category: "Arts & Handicrafts",
    price: 1600,
    groupCount: 12,
    languages: "Marathi, Hindi, English",
    duration: "1 Day",
    cities: "Sawantwadi",
    description: "Explore Sawantwadi's world-famous wooden toy craft. Paint hand-carved wooden animals, fruits, and whistles with bright non-toxic lacquer colors.",
    introduction: "Paint beautiful hand-carved wooden toys with shiny lacquer colors."
  }
];

const seedTours = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("MongoDB connected for seeding...");

    // Delete existing tours
    await Tour.deleteMany({});
    console.log("Cleared existing tours.");

    // Insert new tours
    const inserted = await Tour.insertMany(tours);
    console.log(`Successfully seeded ${inserted.length} tours!`);

    process.exit(0);
  } catch (error) {
    console.error("Error seeding tours:", error.message);
    process.exit(1);
  }
};

seedTours();
